# fly.toml app configuration file generated for flying-couch on 2024-08-13T14:58:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# app = '...'
# primary_region = '...'

[build]
  dockerfile = "Dockerfile"

[http_service]
  processes = ['app']
  internal_port = 5984
  force_https = false  # flycast is http only
  # We don't support auto scaling
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 2


[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/_up"


[mounts]
  source = "couch-data"
  destination = "/opt/couchdb/data"
