# fly.toml app configuration file generated for flying-couch on 2024-08-13T14:58:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# app = '...'
# primary_region = '...'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'cushion'
  destination = '/opt/couchdb/data'

[http_service]
  internal_port = 5984
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 2
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/_up'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
